name: lettutor
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  #UI libraries
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  font_awesome_flutter: ^10.4.0
  chips_choice: ^3.0.0
  flutter_rating_bar: ^4.0.1
  readmore: ^2.2.0
  country_picker: ^2.0.19
  chat_bubbles: ^1.4.1

  #Localizations
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter

  #Plugins for multi media
  cached_network_image: ^3.2.3
  video_player: ^2.6.1
  jitsi_meet_wrapper: ^0.0.6
  url_launcher: ^6.1.10
  syncfusion_flutter_pdfviewer: ^20.4.53

  #Storages & 3rd party
  google_sign_in: ^6.1.0
  firebase_core: ^2.9.0
  shared_preferences: ^2.1.0

  # API
  dio: ^5.0.3
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  build_runner: ^2.3.3

  #State managements
  provider: ^6.0.5
  jwt_decoder: ^2.0.1
  flutter_countdown_timer: ^4.1.0
  chat_gpt_sdk: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Black.ttf
           weight: 900
         - asset: assets/fonts/Roboto-BlackItalic.ttf
           style: italic
           weight: 900
         - asset: assets/fonts/Roboto-Bold.ttf
           weight: 700
         - asset: assets/fonts/Roboto-BoldItalic.ttf
           style: italic
           weight: 700
         - asset: assets/fonts/Roboto-Italic.ttf
           style: italic
         - asset: assets/fonts/Roboto-Light.ttf
           weight: 300
         - asset: assets/fonts/Roboto-LightItalic.ttf
           style: italic
           weight: 300
         - asset: assets/fonts/Roboto-Medium.ttf
           weight: 500
         - asset: assets/fonts/Roboto-MediumItalic.ttf
           style: italic
           weight: 500
         - asset: assets/fonts/Roboto-Regular.ttf
           weight: 400
         - asset: assets/fonts/Roboto-Thin.ttf
           weight: 100
         - asset: assets/fonts/Roboto-ThinItalic.ttf
           style: italic
           weight: 100
